USE deportes;
CREATE SCHEMA bd_prueba;
USE bd_prueba;
CREATE TABLE prueba(
pr_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
pr_x VARCHAR(10) NOT NULL,
PRIMARY KEY(pr_id)
);
INSERT INTO prueba (pr_x) VALUES ('a'), ('b'), ('c'), ('d');
SELECT * FROM prueba;
DELETE FROM prueba WHERE pr_x = 'a';
#TRUNCATE REINICIA LA BASE DE DATOS BORRANDO TODO Y REINICIANDO EL CONTADOR DE LOS ID.
TRUNCATE PRUEBA;
DROP TABLE prueba;
CREATE TABLE prueba(
#EL ZEROFILL RELLENA EL ID CON CEROS A LA IZQUIERDA. CON PONER EL TAMAÑO DEL INT DELANTE DEL INT, PODRIAMOS CONTROLAR CUANTOS CEROS HABRÁ A LA IZQUIERDA DE NUESTRO ID
pr_id INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
pr_x VARCHAR(10) NOT NULL,
PRIMARY KEY(pr_id)
);
#------------------------EXPRESIONES REGULARES----------------------------------------


SHOW TABLES;
DESCRIBE prueba;
DESCRIBE TABLE prueba;

CREATE TABLE prueba2(
pr2_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
pr2_x VARCHAR(10) NOT NULL,
pr2_pr_id INT UNSIGNED NOT NULL,
PRIMARY KEY(pr2_id)
);

INSERT INTO prueba VALUES (null, "Reg 1");
INSERT INTO prueba2 VALUES (null, "Hola", 1);
DROP TABLE prueba2;

DESCRIBE prueba2;

#AÑADIR UN FOREIGN KEY A UNA TABLA YA CREADA
ALTER TABLE prueba2 ADD FOREIGN KEY (pr2_pr_id) REFERENCES prueba(pr_id);

#CAMBIAR NOMBRE TABLA
ALTER TABLE Pepe RENAME Categorias;
ALTER TABLE Juan RENAME Productos;

#AÑADIR CAMPOS EN LAS TABLAS (se añade al final de la tabla)
ALTER TABLE Categorias ADD COLUMN precio DECIMAL(10,2);

#AÑADIR CAMPOS EN LAS TABLAS EN UNA POSICION DETERMINADA.
ALTER TABLE Categorias ADD COLUMN descripcion MEDIUMTEXT AFTER pr_x;

#AÑADIR CAMPOS AL PRINCIPIO DE LA TABLA
ALTER TABLE Categorias ADD COLUMN primero INT FIRST;

#BORRAR UNA COLUMNA.
ALTER TABLE Categorias DROP COLUMN primero;

#MODIFICAR UN TIPO DE CAMPO Y EL NOMBRE DEL MISMO
ALTER TABLE Categorias CHANGE COLUMN pr_x nombre VARCHAR(50);

#MODIFICAR SOLO EL TIPO DEL CAMPO(DE INT A VARCHAR, POR EJEMPLO)
ALTER TABLE Categorias MODIFY COLUMN descripcion VARCHAR(225);

DROP TABLE categorias, productos;



